language: python
os:
  - linux
  - osx
dist:
  - xenial

addons:
  apt:
    packages:
    - swig
    - libssl-dev
    - libssl1.0.0
  homebrew:
    packages:
    - swig
    - openssl

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

jobs:
  allow_failures:
    - python: "nightly"

install:
  - travis_retry pip install setuptools Twisted pytest
  - python setup.py install

script: python setup.py test
